# Dependencies
# markdown:         redcarpet
highlighter:      pygments

# Permalinks
# permalink:        pretty
# relative_permalinks: true

# Setup
title:            UNNC MOBA
tagline:          'A moba game made by UNNC students'
description:      'Hey, we are making a moba game like DOTA or LOL,
is that cool?'
# url:              http://meowalienowo.github.io/
baseurl:          /MOBAGames

author:
  name:           'UNNC MOBA Game project'

paginate:         5

# Custom vars
version:          1.0

github:
  repo:           https://github.com/MeowAlienOwO/MOBAGames

